# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'newappointment.ui'
#
# Created: Wed Aug  5 13:03:30 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(609, 449)
        self.horizontalLayout_5 = QtGui.QHBoxLayout(Dialog)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtGui.QLabel(Dialog)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.labelPatientID = QtGui.QLabel(Dialog)
        self.labelPatientID.setFrameShape(QtGui.QFrame.Box)
        self.labelPatientID.setFrameShadow(QtGui.QFrame.Sunken)
        self.labelPatientID.setObjectName("labelPatientID")
        self.horizontalLayout.addWidget(self.labelPatientID)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.buttonPatientSelect = QtGui.QPushButton(Dialog)
        self.buttonPatientSelect.setObjectName("buttonPatientSelect")
        self.verticalLayout.addWidget(self.buttonPatientSelect)
        self.verticalLayout_4.addLayout(self.verticalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.txtRegDate = QtGui.QLineEdit(Dialog)
        self.txtRegDate.setObjectName("txtRegDate")
        self.horizontalLayout_2.addWidget(self.txtRegDate)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.txtRefDoc = QtGui.QLineEdit(Dialog)
        self.txtRefDoc.setObjectName("txtRefDoc")
        self.horizontalLayout_3.addWidget(self.txtRefDoc)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.cbxPriority = QtGui.QComboBox(Dialog)
        self.cbxPriority.setObjectName("cbxPriority")
        self.cbxPriority.addItem("")
        self.cbxPriority.addItem("")
        self.cbxPriority.addItem("")
        self.horizontalLayout_4.addWidget(self.cbxPriority)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.txtNotes = QtGui.QTextEdit(Dialog)
        self.txtNotes.setObjectName("txtNotes")
        self.verticalLayout_2.addWidget(self.txtNotes)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.line = QtGui.QFrame(Dialog)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_5.addWidget(self.line)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.buttonAssignDate = QtGui.QPushButton(Dialog)
        self.buttonAssignDate.setObjectName("buttonAssignDate")
        self.verticalLayout_3.addWidget(self.buttonAssignDate)
        self.buttonBookWithoutDate = QtGui.QPushButton(Dialog)
        self.buttonBookWithoutDate.setObjectName("buttonBookWithoutDate")
        self.verticalLayout_3.addWidget(self.buttonBookWithoutDate)
        self.buttonProceed = QtGui.QPushButton(Dialog)
        self.buttonProceed.setObjectName("buttonProceed")
        self.verticalLayout_3.addWidget(self.buttonProceed)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.buttonCancel = QtGui.QPushButton(Dialog)
        self.buttonCancel.setObjectName("buttonCancel")
        self.verticalLayout_3.addWidget(self.buttonCancel)
        self.verticalLayout_5.addLayout(self.verticalLayout_3)
        self.horizontalLayout_5.addLayout(self.verticalLayout_5)
        self.label_2.setBuddy(self.buttonPatientSelect)
        self.label_3.setBuddy(self.txtRegDate)
        self.label_4.setBuddy(self.txtRefDoc)
        self.label_5.setBuddy(self.cbxPriority)
        self.label_6.setBuddy(self.txtNotes)

        self.retranslateUi(Dialog)
        self.cbxPriority.setCurrentIndex(1)
        QtCore.QObject.connect(self.buttonCancel, QtCore.SIGNAL("clicked()"), Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">New Appointment</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Patient ID:", None, QtGui.QApplication.UnicodeUTF8))
        self.labelPatientID.setText(QtGui.QApplication.translate("Dialog", "<html><head/><body><p><span style=\" font-style:italic;\">Please select patient</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonPatientSelect.setText(QtGui.QApplication.translate("Dialog", "Select Patient", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Registration Date:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Refferring Doctor:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Priority:", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxPriority.setItemText(0, QtGui.QApplication.translate("Dialog", "Urgent", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxPriority.setItemText(1, QtGui.QApplication.translate("Dialog", "Medium", None, QtGui.QApplication.UnicodeUTF8))
        self.cbxPriority.setItemText(2, QtGui.QApplication.translate("Dialog", "Low", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Notes:", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonAssignDate.setText(QtGui.QApplication.translate("Dialog", "Assign Date", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonBookWithoutDate.setText(QtGui.QApplication.translate("Dialog", "Book Without Date", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonProceed.setText(QtGui.QApplication.translate("Dialog", "Book && Proceed", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonCancel.setText(QtGui.QApplication.translate("Dialog", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

