# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Wed Jun  3 16:46:51 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(682, 436)
        MainWindow.setMinimumSize(QtCore.QSize(680, 435))
        MainWindow.setMaximumSize(QtCore.QSize(700, 450))
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.centralWidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.labelTitle = QtGui.QLabel(self.centralWidget)
        self.labelTitle.setObjectName("labelTitle")
        self.verticalLayout_3.addWidget(self.labelTitle)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.buttonNewPatient = QtGui.QPushButton(self.centralWidget)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/apnea/resources/icons/add_patients.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonNewPatient.setIcon(icon)
        self.buttonNewPatient.setObjectName("buttonNewPatient")
        self.verticalLayout_2.addWidget(self.buttonNewPatient)
        self.buttonBookAppointment = QtGui.QPushButton(self.centralWidget)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/apnea/resources/icons/book_appointment.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonBookAppointment.setIcon(icon1)
        self.buttonBookAppointment.setObjectName("buttonBookAppointment")
        self.verticalLayout_2.addWidget(self.buttonBookAppointment)
        self.buttonViewAppointments = QtGui.QPushButton(self.centralWidget)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/apnea/resources/icons/view_appointments.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonViewAppointments.setIcon(icon2)
        self.buttonViewAppointments.setObjectName("buttonViewAppointments")
        self.verticalLayout_2.addWidget(self.buttonViewAppointments)
        self.buttonViewPatients = QtGui.QPushButton(self.centralWidget)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/apnea/resources/icons/view_patients.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonViewPatients.setIcon(icon3)
        self.buttonViewPatients.setObjectName("buttonViewPatients")
        self.verticalLayout_2.addWidget(self.buttonViewPatients)
        self.buttonSetAvailableDates = QtGui.QPushButton(self.centralWidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/apnea/resources/icons/set_dates.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonSetAvailableDates.setIcon(icon4)
        self.buttonSetAvailableDates.setObjectName("buttonSetAvailableDates")
        self.verticalLayout_2.addWidget(self.buttonSetAvailableDates)
        self.buttonReports = QtGui.QPushButton(self.centralWidget)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/apnea/resources/icons/reports.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonReports.setIcon(icon5)
        self.buttonReports.setObjectName("buttonReports")
        self.verticalLayout_2.addWidget(self.buttonReports)
        self.buttonSettings = QtGui.QPushButton(self.centralWidget)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/apnea/resources/icons/settings.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonSettings.setIcon(icon6)
        self.buttonSettings.setObjectName("buttonSettings")
        self.verticalLayout_2.addWidget(self.buttonSettings)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        spacerItem = QtGui.QSpacerItem(20, 28, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.buttonAbout = QtGui.QPushButton(self.centralWidget)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/apnea/resources/icons/about.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonAbout.setIcon(icon7)
        self.buttonAbout.setObjectName("buttonAbout")
        self.horizontalLayout.addWidget(self.buttonAbout)
        self.buttonHelp = QtGui.QPushButton(self.centralWidget)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/apnea/resources/icons/help.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonHelp.setIcon(icon8)
        self.buttonHelp.setObjectName("buttonHelp")
        self.horizontalLayout.addWidget(self.buttonHelp)
        self.buttonQuit = QtGui.QPushButton(self.centralWidget)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/apnea/resources/icons/quit.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonQuit.setIcon(icon9)
        self.buttonQuit.setObjectName("buttonQuit")
        self.horizontalLayout.addWidget(self.buttonQuit)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.labelLogo = QtGui.QLabel(self.centralWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelLogo.sizePolicy().hasHeightForWidth())
        self.labelLogo.setSizePolicy(sizePolicy)
        self.labelLogo.setMaximumSize(QtCore.QSize(320, 320))
        self.labelLogo.setAutoFillBackground(False)
        self.labelLogo.setText("")
        self.labelLogo.setPixmap(QtGui.QPixmap(":/apnea/resources/icons/logo.jpg"))
        self.labelLogo.setObjectName("labelLogo")
        self.horizontalLayout_2.addWidget(self.labelLogo)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar()
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 682, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.actionQuit = QtGui.QAction(MainWindow)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("../icons/quit.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon10)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAbout = QtGui.QAction(MainWindow)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("../icons/about.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon11)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionAbout)
        self.menuFile.addAction(self.actionQuit)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.buttonQuit, QtCore.SIGNAL("clicked()"), MainWindow.close)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL("triggered()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "Apnea", None, QtGui.QApplication.UnicodeUTF8))
        self.labelTitle.setText(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">Apnea</span></p><p>Sleep Laboratory Patient Management Suite</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonNewPatient.setText(QtGui.QApplication.translate("MainWindow", "Add a New Patient", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonBookAppointment.setText(QtGui.QApplication.translate("MainWindow", "Book an Appointment", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonViewAppointments.setText(QtGui.QApplication.translate("MainWindow", "View Appointments", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonViewPatients.setText(QtGui.QApplication.translate("MainWindow", "View Patient Archive", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonSetAvailableDates.setText(QtGui.QApplication.translate("MainWindow", "Set Available Dates for Appointments", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonReports.setText(QtGui.QApplication.translate("MainWindow", "Reports", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonSettings.setText(QtGui.QApplication.translate("MainWindow", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonHelp.setText(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "About", None, QtGui.QApplication.UnicodeUTF8))

import icons_rc
